name: Create zipped module
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create zipped module
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'dss.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig makefile'
    - name: Upload zipped module as release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        tag: v1.0.1
        artifacts: "dss.zip"
        token: ${{ secrets.GITHUB_TOKEN }}       
